"""Add tier1 AI features columns

Revision ID: 45267c161a7e
Revises: 8f20f1691fc4
Create Date: 2025-10-21 00:07:20.499236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45267c161a7e'
down_revision: Union[str, None] = '8f20f1691fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('code_review', sa.JSON(), nullable=True))
    op.add_column('code_files', sa.Column('quality_metrics', sa.JSON(), nullable=True))
    op.add_column('code_files', sa.Column('architecture_data', sa.JSON(), nullable=True))
    op.add_column('code_files', sa.Column('mentor_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_files', 'mentor_insights')
    op.drop_column('code_files', 'architecture_data')
    op.drop_column('code_files', 'quality_metrics')
    op.drop_column('code_files', 'code_review')
    # ### end Alembic commands ###
